camera:
  model: X-T20
  firmware: 1.00

processing:
  colorSpace: sRGB

xRawStudio:
  version: 1.12.0.0
  serialNumber: 
  simulationsPath: /Users/hcbt/Library/Application Support/com.fujifilm.denji/X RAW STUDIO/X-T20/X-T20_0100