camera:
  model: X-T20
  firmware: 1.00

processing:
  color_space: sRGB

x_raw_studio:
  version: 1.12.0.0
  serial_number: 
  simulations_path: /Users/hcbt/Library/Application Support/com.fujifilm.denji/X RAW STUDIO/X-T20/X-T20_0100